### ISSUE TITLE
v2.01: greylist plugin fails with redis

### ISSUE THREAD

**Issue by LuckyFellow** [benningm/mtpolicyd#14]
Using redis with greylist plugin gives this error message:

Starting postfix policy server: mtpolicyd could not initialize plugin greylist: no connection memcached configured! at /usr/local/share/perl/5.20.2/Mail/MtPolicyd/Role/Connection.pm line 55.

This is caused by /usr/local/share/perl/5.20.2/Mail/MtPolicyd/Plugin/Greylist.pm

line 40:
```
with 'Mail::MtPolicyd::Role::Connection' => {
  name => 'memcached',
  type => 'Memcached',
};
```

replacing it with:
```
with 'Mail::MtPolicyd::Role::Connection' => {
  name => 'redis',
  type => 'Redis',
};
```

Makes it stop complain at startup, though it's no fix.
The module hardwires _memcached_handle and calls ->delete on it, which does not fit for Redis.

**Comment by benningm** [comment]
The Greylisting plugin is written for memcached. It does not support Redis at the moment.

To make it work with Redis you have to adjust more than just the connection handle because the command set of redis and memcached is not compatible.
