### ISSUE TITLE
Error on Socket.pm

### ISSUE THREAD

**Issue by setiseta** [benningm/mtpolicyd#22]
I'm getting following error:
error while processing request: Bad arg length for Socket::pack_sockaddr_in, length is 0, should be 4 at /usr/local/lib/perl5/5.24.0/x86_64-linux/Socket.pm line 834, <GEN2> line 28.\n

Any hints how to fix this one?

Greetings

**Comment by benningm** [comment]
Sorry, can fix this without more details.

Seems to be an old issue. Reopen if problem is still there.
