### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by falon** [benningm/mtpolicyd#27]
Hello,

 with module "LdapUserConfig"
 after some while the LDAP search doesn't work no more and mtpolicyd returns this error:

Jun  7 12:36:29 tst-example mtpolicyd[21133]: accounting: ldap search failed: Broken pipe at /usr/share/perl5/vendor_perl/Mail/MtPolicyd/Plugin/LdapUserConfig.pm line 65.\n

In LDAP log I only see the bind without error, but not any search.

If I restart mtpolicyd, then it works as expected. Why?

**Comment by benningm** [comment]
Can you check if the LDAP server closes the connection due to a connection timeout setting?

**Comment by falon** [comment]
Yes, the LDAP server closes the connection when the idle timeout occurs... I think mtpolicyd should deal with this event.

I can't understand why the LDAP BIND still works, so the LDAP connection works. But this error in search phase occurs.

**Comment by benningm** [comment]
mtpolicyd implements a connection pool and reuses connections.
The bind is only done on initial connect.

I think we can change the code to shutdown the connection on certain(connection) errors
so it will be reopened for following calls.

Additional it would be a good thing to test if the connection handle is alive before returning it from the connection pool.
But that may not be possible without sending something.

Do you have an test environment you can use to test changes?

**Comment by falon** [comment]
Yes, I can test changes. If you have some idea I can test if the problem still occurs after change.

**Comment by falon** [comment]
Yes, I was confused about LDAP BIND from multiple connection....
I think it could be tested the closed handle to reopen the connection...

**Comment by falon** [comment]
Wow!
It works!

**Comment by benningm** [comment]
Nice to hear :-) I'll push a new release of mtpolicyd with the changes.

If you think that your configuration may be of intresst for others it would be great if you could provide it as an example for inclusion in the repository.

**Comment by benningm** [comment]
Just released v2.03
