### ISSUE TITLE
Web site mtpolicyd.org is not working

### ISSUE THREAD

**Issue by kepi** [benningm/mtpolicyd#28]
403 when trying to access https://mtpolicyd.org/ for at least 10 days.

**Comment by benningm** [comment]
Regarding to the new data protection law in EU i had to check thru all my online presences.

Since the website content is mostly based on POD documentation which is also available from the source and browsable on CPAN/MetaCPAN i decided to save the time and turn it down.

The mailing list was also very low traffic. Please open issues here.

**Comment by kepi** [comment]
Oh, that's really a shame. I think website is really important for first contact with software and I wouldn't be probably using mtpolicyd without it.

As I'm EU citizen and have to deal with GDPR on everyday basis in work, maybe I can help you with questions? I'm not lawyer, but mtpolicyd website was super simple. If you just have documentation there, don't use cookies, dont have any signup/login you don't need to do anything. GDPR is only about collecting personal data.

I understand you with browsable on CPAN and I'm former Perl programmer so I should be familiar with it but mtpolicyd is software I use, not Perl module so it wouldn't cross my mind.

**Comment by kepi** [comment]
It really is not needed. When you are not collecting data, you don't have any obligation to add information. GDPR looks scary but it is not. Logging is ok for GDPR purposes without any consent if you do not store it forever.

Also there is no intention from any official party to prosecute small websites, GDPR is primarily targeted at big players and abuse of personal data.

**Comment by benningm** [comment]
The mtpolicyd.org website is back online!
