### ISSUE TITLE
Documentation spelling errors (show up in Debian lintian reports in the man pages)

### ISSUE THREAD

**Issue by kitterma** [benningm/mtpolicyd#29]
usr/share/man/man1/mtpolicyd.1p.gz Specifiy Specify
    usr/share/man/man1/mtpolicyd.1p.gz registred registered
    usr/share/man/man1/mtpolicyd.1p.gz registred registered
    usr/share/man/man3/Mail::MtPolicyd::Client::Response.3pm.gz reponse response
    usr/share/man/man3/Mail::MtPolicyd::Connection::Memcached.3pm.gz seperated separated
    usr/share/man/man3/Mail::MtPolicyd::Cookbook::BasicPlugin.3pm.gz basicly basically
    usr/share/man/man3/Mail::MtPolicyd::Cookbook::BasicPlugin.3pm.gz everytime every time
    usr/share/man/man3/Mail::MtPolicyd::Cookbook::ExtendedPlugin.3pm.gz theres there's
    usr/share/man/man3/Mail::MtPolicyd::Plugin::Condition.3pm.gz futher further
    usr/share/man/man3/Mail::MtPolicyd::Plugin::CtIpRep.3pm.gz defered deferred
    usr/share/man/man3/Mail::MtPolicyd::Plugin::CtIpRep.3pm.gz specifiy specify
    usr/share/man/man3/Mail::MtPolicyd::Plugin::CtIpRep.3pm.gz specifiy specify
    usr/share/man/man3/Mail::MtPolicyd::Plugin::Greylist.3pm.gz defered deferred
    usr/share/man/man3/Mail::MtPolicyd::Plugin::Greylist.3pm.gz defered deferred
    usr/share/man/man3/Mail::MtPolicyd::Plugin::LdapUserConfig.3pm.gz seperated separated
    usr/share/man/man3/Mail::MtPolicyd::Plugin::SMTPVerify.3pm.gz recieve receive
    usr/share/man/man3/Mail::MtPolicyd::Plugin::SMTPVerify.3pm.gz returnes returns
    usr/share/man/man3/Mail::MtPolicyd::Plugin::SqlList.3pm.gz wether whether
    usr/share/man/man3/Mail::MtPolicyd::Plugin::Stress.3pm.gz futher further
    usr/share/man/man3/Mail::MtPolicyd::Plugin::Stress.3pm.gz futher further

**Comment by benningm** [comment]
Fixed in 606e88f49ecd13595a454614ed812a47dce26438

Thanks for reporting.
