### ISSUE TITLE
could not initialize plugin greylist: no sql database initialized

### ISSUE THREAD

**Issue by nysander** [benningm/mtpolicyd#5]
I have installed mtpolicyd from debian package on ubuntu 12.04 but I cannot start it. How can I initialise database?

full error:

```
* Starting postfix policy server mtpolicyd
could not initialize plugin greylist: no sql database initialized, but required for plugin greylist at /usr/share/perl5/Mail/MtPolicyd/Plugin/Role/SqlUtils.pm line 14.
[fail]
invoke-rc.d: initscript mtpolicyd, action "start" failed.
dpkg: error processing package mtpolicyd (--configure):
...
```

**Comment by ovizii** [comment]
Got a similar issue, added the Debian 8 repo and installed: 
apt-get install mtpolicyd 

result:
`Starting postfix policy server: mtpolicydcould not initialize plugin greylist: no sql database initialized, but required for plugin greylist at /usr/share/perl5/Mail/MtPolicyd/Plugin/Role/SqlUtils.pm line 14.
 (warning).
invoke-rc.d: initscript mtpolicyd, action "start" failed.
dpkg: error processing package mtpolicyd (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 mtpolicyd
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by benningm** [comment]
Should no longer be valid for official debian packages
