### ISSUE TITLE
Default table type

### ISSUE THREAD

**Issue by anomaly256** [benningm/mtpolicyd#6]
More of a feature request than an issue - can we have a mechanism to specify the default table type in the mtpolicyd.conf?  For example, so we can specify InnoDB for use on a Galera cluster without having to hand-edit any tables mtpolicyd automatically creates after the fact?

If you're open to this, I'm happy to write the code and do a PR.

Cheers,
Wes

**Comment by kepi** [comment]
It would be great to have this. We are setting servers with mtpolicyd from ansible and only option now is  create innodb tables in advance.  I see that problematic because if somebody changes config to add new plugin, we are in same troubles again.

**Comment by benningm** [comment]
has been implemented in #26 

Please test if it fits your needs and comment in PR

**Comment by anomaly256** [comment]
Thanks!
