### ISSUE TITLE
Debian packages are missing some important dependancies

### ISSUE THREAD

**Issue by anomaly256** [benningm/mtpolicyd#8]
When installing from the Debian packages as stated at the [Repository / Download](http://software.opensuse.org/download.html?project=home%3Abenningm%3Amtpolicyd&package=mtpolicyd) page, these dependencies are missing in the deb metadata (at least for the Debian 7 packages):

```
libjson-perl
libnet-ldap-perl
libmail-spf-perl
```

(note: dependancies for other plugins might be missing as well but these are the only ones I've come across in our specific use-case so far)
This means the install script fails part-way and the user is required to manually install these packages before it can continue

**Comment by anomaly256** [comment]
also
```
libnet-server-perl
```

**Comment by ikar-us** [comment]
Yes, I encountered this, too, with Debian 8.
Probably it wasn't noticed in developing on servers where the packages are installed anyway.

**Comment by benningm** [comment]
Debian packaging has been removed from upstream repository and is now part of debian.
It should be fixed in Debians package. Otherwise please open a bug there.
