### ISSUE TITLE
Init script in Debian packages doesn't exit

### ISSUE THREAD

**Issue by anomaly256** [benningm/mtpolicyd#9]
The script placed in to /etc/init.d/ by the Debian 7 package (possibly 8 as well, haven't tested it yet) never returns, causing initial install to appear to hang even though it succeeded and mtpolicyd launched.  This also has an effect when manually stopping/starting the service, and will likely cause problems on reboot as well.

**Comment by benningm** [comment]
Debian packaging has been removed from upstream repository and is now part of debian.
It should be fixed in Debians package. Otherwise please open a bug there.
